# ----------------------------------------
# CONNEXION À LA BASE DE DONNÉES MYSQL
# ----------------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/publication_article?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ----------------------------------------
# CONFIGURATION DE L'ORM (HIBERNATE / JPA)
# ----------------------------------------
# Affiche les requêtes SQL générées dans la console (très utile pour le débogage)
spring.jpa.show-sql=true

# Formate le SQL dans la console pour qu'il soit lisible
spring.jpa.properties.hibernate.format_sql=true

# LA MAGIE DE SPRING : Met à jour la structure des tables automatiquement
spring.jpa.hibernate.ddl-auto=update